
export default {
  ActionTypes: {
    GET_WEATHER_FORECAST_PENDING: 'GET_WEATHER_FORECAST_PENDING',
    GET_WEATHER_FORECAST_SUCCESS: 'GET_WEATHER_FORECAST_SUCCESS',
    GET_WEATHER_FORECAST_FAILED: 'GET_WEATHER_FORECAST_FAILED',
    GET_SEARCHING_HISTORY: 'GET_SEARCHING_HISTORY',
    GET_WEEK_WEATHER_FORECAST_PENDING: 'GET_WEEK_WEATHER_FORECAST_PENDING',
    GET_WEEK_WEATHER_FORECAST_SUCCESS: 'GET_WEEK_WEATHER_FORECAST_SUCCESS',
    GET_WEEK_WEATHER_FORECAST_FAILED: 'GET_WEEK_WEATHER_FORECAST_FAILED',
  },
  States: {
    SUCCESS: 'SUCCESS',
    FAIL: 'FAIL',
    PENDING: 'PENDING'
  },
  API_WEATHER_KEY:'0d675c50e0a6e4d4067db2312278353f',
  DEFAULT_CITY:'Kiev'
}
